### ISSUE TITLE
Missing items

### ISSUE THREAD

**Issue by cheeseslicer** [Zazou89/BetterBags_WorldEvents#4]
223646, -- Memory of the Eastern Kingdoms    Is missing from the list entirely and then when I was looking through to add it in manually myself I noticed that you have item 223644 listed as 223644, -- Memory of Northrend instead of 223644, -- Memory of Kalimdor

**Comment by KatyPurry** [comment]
Thank you, it's fixed with https://github.com/Zazou89/BetterBags_WorldEvents/releases/tag/1.3.3

**Comment by Zazou89** [comment]
Thank you, it's fixed with the latest [release](https://github.com/Zazou89/BetterBags_WorldEvents/releases/tag/1.3.3).
