### ISSUE TITLE
Missing Worgen Female Mask

### ISSUE THREAD

**Issue by maddin77** [Zazou89/BetterBags_WorldEvents#6]
https://www.wowhead.com/item=49215/worgen-female-mask

is missing from the hallows end list

**Comment by KatyPurry** [comment]
Hi @maddin77 ! 
Thank you, it's done with https://github.com/Zazou89/BetterBags_WorldEvents/releases/tag/v1.6.1

**Comment by Zazou89** [comment]
Hi @maddin77 !
Thank you, it's done with https://github.com/Zazou89/BetterBags_WorldEvents/releases/tag/v1.6.1
